package br.featureref.organicref.model.entities;

public enum StatementKind {

	ASSERT_STATEMENT,
	BLOCK,
	BREAK_STATEMENT,
	CONSTRUCTOR_INVOCATION,
	CONTINUE_STATEMENT,
	DO_STATEMENT,
	EMPTY_STATEMENT,
	ENHANCEDFOR_STATEMENT,
	EXPRESSION_STATEMENT,
	FOR_STATEMENT,
	IF_STATEMENT,
	LABELED_STATEMENT,
	RETURN_STATEMENT,
	SUPERCONSTRUCTOR_INVOCATION,
	SWITCH_CASE,
	SWITCH_STATEMENT,
	SYNCRONIZED_STATEMENT,
	THROW_STATEMENT,
	TRY_STATEMENT,
	TYPEDECLARATION_STATEMENT,
	VARIABLEDECLARATION_STATEMENT,
	WHILE_STATEMENT,
	YIELD_STATEMENT;
}
