package br.featureref.organicref.quality.metrics;

public enum ThresholdTypes
{
  CYCLOMATIC_COMPLEXITY_75_PERCENTIL, COUPLING_DISPERSION_MEDIAN, COUPLING_INTENSITY_MEDIAN, CYCLOMATIC_COMPLEXITY_MEDIAN, NUMBER_STATEMENTS_MEDIAN,
  NUMBER_CLIENTS_75_PERCENTIL,
}
